MODULE_NAME = amlogic-encoder
obj-m = $(MODULE_NAME).o
$(MODULE_NAME)-y += encoder.o

PR_FMT = $(subst amlogic-,,$(MODULE_NAME))
PR_FMT_DEFINE="-Dpr_fmt(fmt)= \"[$(PR_FMT)]: \" fmt"
ccflags-y += $(PR_FMT_DEFINE)
